-- Seed public.organizations from BC_Transition_Houses_Safe_Homes.csv
-- Generated from the CSV; ids match the slugs used by the local CSV fallback.
-- population_categories, service_categories and more_info are left to the
-- prepare_organization_import trigger. Safe to re-run: existing ids are skipped.

insert into public.organizations
  (id, location, organization, program, phone, toll_free, text_only, type, updated_at_label)
values
  ('100-mile-house-safe-home-1', '100 Mile House', 'Canadian Mental Health Association - South Cariboo Branch', '100 Mile House Safe Home', '1-800-563-0808', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('abbotsford-transition-house-2', 'Abbotsford', 'SARA for Women Society', 'Abbotsford Transition House', '604-852-6008', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('libra-transition-house-3', 'Aldergrove', 'Ishtar Women''s Resource Society', 'Libra Transition House', '604-857-5797', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('snxlhh-or-nuxalk-transition-house-4', 'Bella Coola', 'Nuxalk Transition House Society', 'Snxlhh or Nuxalk Transition House', '1-877-799-0070', '1-877-799-0070', null, 'Transition House', 'From BC transition houses CSV'),
  ('dixon-transition-house-5', 'Burnaby', 'Dixon Transition Society', 'Dixon Transition House', '604-298-3454', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('eagle-s-nest-transition-house-6', 'Burns Lake', 'Prince George and District Elizabeth Fry Society', 'Eagle''s Nest Transition House', '250-692-5720', null, '250-692-7559', 'Transition House', 'From BC transition houses CSV'),
  ('ann-elmore-transition-house-7', 'Campbell River', 'Campbell River and North Island Transition Society', 'Ann Elmore Transition House', '250-286-3666', '1-800-667-2188', '250-895-1773', 'Transition House', 'From BC transition houses CSV'),
  ('castlegar-safe-home-8', 'Castlegar', 'Castlegar Community Services Society', 'Castlegar Safe Home', '250-608-3710', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('chetwynd-safe-home-9', 'Chetwynd', 'South Peace Community Resources Society', 'Chetwynd Safe Home', '250-788-1976', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('linda-krystina-safe-house-10', 'Chetwynd', 'The Linda Krystina Housing Society', 'Linda Krystina Safe House', '250-401-8079', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('ann-davis-transition-house-11', 'Chilliwack', 'Ann Davis Transition Society', 'Ann Davis Transition House', '604-792-3116', null, '604-819-3557', 'Transition House', 'From BC transition houses CSV'),
  ('ann-davis-women-s-centre-12', 'Chilliwack', 'Ann Davis Transition Society', 'Ann Davis Women''s Centre', '604-391-1993', null, '604-819-3557', 'Transition House', 'From BC transition houses CSV'),
  ('wilma-s-transition-house-13', 'Chilliwack', 'Wilma''s Transition Society', 'Wilma''s Transition House', '604-858-0468', '1-888-558-0468', null, 'Transition House', 'From BC transition houses CSV'),
  ('clearwater-safe-home-14', 'Clearwater', 'Yellowhead Community Services Society', 'Clearwater Safe Home', '250-674-2135', '1-855-674-2135', null, 'Safe Home', 'From BC transition houses CSV'),
  ('joy-s-place-15', 'Coquitlam', 'Tri-City Transitions Society', 'Joy''s Place', '604-492-1700', '1-800-563-0808', null, 'Transition House', 'From BC transition houses CSV'),
  ('lilli-house-16', 'Courtenay', 'Comox Valley Transition Society', 'Lilli House', '250-338-1227', null, '250-218-4034', 'Transition House', 'From BC transition houses CSV'),
  ('kootenay-haven-transition-house-17', 'Cranbrook', 'Canadian Mental Health Association for the Kootenays', 'Kootenay Haven Transition House', '250-426-4887', '1-800-200-3003', null, 'Transition House', 'From BC transition houses CSV'),
  ('irvine-house-safe-home-program-18', 'Creston', 'Kootenai Community Centre Society', 'Irvine House Safe Home Program', '250-428-6856', null, '250-402-0068', 'Safe Home', 'From BC transition houses CSV'),
  ('mizpah-transition-house-19', 'Dawson Creek', 'South Peace Community Resources Society', 'Mizpah Transition House', '250-782-9176', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('azure-place-20', 'Delta', 'W.I.N.G.S. Fellowship Ministries (Women in Need Gaining Strength)', 'Azure Place', '604-957-1556', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('somenos-transition-house-21', 'Duncan', 'Cowichan Women Against Violence Society', 'Somenos Transition House', '250-748-8544', null, '250-701-1563', 'Transition House', 'From BC transition houses CSV'),
  ('lelum-u-tu-s-tsa-elh-teyten-house-of-honorable-mothers-22', 'Duncan', 'Hiiye''yu Lelum (House of Friendship) Society', 'Lelum ''u tu S''tsa''-elh teyten (House of Honorable Mothers)', '250-732-7788', null, '250-748-2242', 'Transition House', 'From BC transition houses CSV'),
  ('elk-valley-women-s-transition-house-23', 'Elkford', 'Elkford Women''s Task Force Society', 'Elk Valley Women''s Transition House', '250-946-6004', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('fnafs-women-s-transition-house-24', 'Fort Nelson', 'Fort Nelson Aboriginal Friendship Society', 'FNAFS Women''s Transition House', '250-774-4742', null, '250-774-2993', 'Transition House', 'From BC transition houses CSV'),
  ('fireweed-safe-haven-25', 'Fort St. James', 'Fireweed Collective Society', 'Fireweed Safe Haven', '250-996-8000', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('meaope-transition-house-26', 'Fort St. John', 'North Peace Community Resources Society', 'Meaope Transition House', '250-785-5208', null, '250-785-6021', 'Transition House', 'From BC transition houses CSV'),
  ('gold-river-safe-home-27', 'Gold River', 'Campbell River and North Island Transition Society', 'Gold River Safe Home', '250-286-3666', '1-800-667-2188', null, 'Safe Home', 'From BC transition houses CSV'),
  ('golden-safe-home-28', 'Golden', 'Golden Women''s Centre Society', 'Golden Safe Home', '250-344-2101', null, '250-344-5317', 'Safe Home', 'From BC transition houses CSV'),
  ('boundary-women-s-transition-house-29', 'Grand Forks', 'Boundary Women''s Coalition', 'Boundary Women''s Transition House', '250-442-3131', '1-855-441-3131', null, 'Transition House', 'From BC transition houses CSV'),
  ('cedar-rose-30', 'Hazelton', 'Northern Society for Domestic Peace', 'Cedar Rose', '778-641-4445', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('jean-scott-transition-house-31', 'Hope', 'Cedar Strong Prevention and Intervention Society', 'Jean Scott Transition House', '604-869-5191', '1-877-869-5191', '604-869-1872', 'Transition House', 'From BC transition houses CSV'),
  ('women-s-information-and-safe-home-wish-32', 'Invermere', 'Family Dynamix Association', 'Women''s Information and Safe Home (WISH)', '250-342-5566', '1-800-200-3003', '250-341-3963', 'Safe Home', 'From BC transition houses CSV'),
  ('y-women-s-emergency-shelter-33', 'Kamloops', 'YWCA BC', 'Y Women''s Emergency Shelter', '250-374-6162', null, '250-682-7931', 'Transition House', 'From BC transition houses CSV'),
  ('kaslo-safe-home-34', 'Kaslo', 'Kaslo Community Services Society', 'Kaslo Safe Home', '250-353-7691', null, '250-354-4357', 'Safe Home', 'From BC transition houses CSV'),
  ('kelowna-women-s-shelter-35', 'Kelowna', 'Central Okanagan Emergency Shelter Society', 'Kelowna Women''s Shelter', '250-763-1040', null, '236-970-0704', 'Transition House', 'From BC transition houses CSV'),
  ('dunmore-place-36', 'Kitimat', 'The Tamitik Status of Women Association', 'Dunmore Place', '250-632-6070', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('ishtar-transition-house-37', 'Langley', 'Ishtar Women''s Resource Society', 'Ishtar Transition House', '604-530-9442', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('sa-koh-housing-38', 'Lower Post', 'Lower Post Housing Society', 'Sa-Koh Housing', '250-779-3078', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('stqaka7st-mc-hold-my-hand-lil-wat-nation-transition-house-39', 'Lil''wat Nation', 'Hans Knakst Tsitxw Society', 'Stqaka7stúmc – Hold my hand Lil''wat Nation Transition House', '604-384-7247', '1-833-512-0664', null, 'Transition House', 'From BC transition houses CSV'),
  ('lillooet-safe-home-40', 'Lillooet', 'Lillooet Friendship Centre Society', 'Lillooet Safe Home', '250-256-4146', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('helping-hands-transition-house-41', 'Lytton', 'Hans Knakst Tsitxw Society', 'Helping Hands Transition House', '778-254-0217', '1-800-318-4455', '778-254-8582', 'Transition House', 'From BC transition houses CSV'),
  ('jonduh-wuts-uh-from-here-on-safe-home-42', 'Mackenzie', 'Mackenzie Counselling Services Society', 'Jonduh Wuts''uh From Here On (Safe Home)', '250-997-6595', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('cythera-transition-house-43', 'Maple Ridge', 'Cythera Transition House Society', 'Cythera Transition House', '604-467-9966', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('tlaa-juuhldaa-naay-transition-house-44', 'Massett', 'Haida Gwaii Society for Community Peace', 'Tlaa Juuhldaa Naay Transition House', '250-626-4666', '1-877-626-4677', '250-626-9163', 'Transition House', 'From BC transition houses CSV'),
  ('mission-transition-house-45', 'Mission', 'SARA for Women Society', 'Mission Transition House', '604-826-7800', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('nakusp-safe-home-46', 'Nakusp', 'Arrow and Slocan Lakes Community Services', 'Nakusp Safe Home', '250-265-1843', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('haven-house-47', 'Nanaimo', 'Haven Society', 'Haven House', '250-756-0616', '1-888-756-0616', '250-756-2452', 'Transition House', 'From BC transition houses CSV'),
  ('cedar-woman-house-48', 'Nanaimo', 'Snuneymuxw First Nation', 'Cedar Woman House', '250-591-5580', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('aimee-beaulieu-transition-house-49', 'Nelson', 'The Nelson Community Service Society', 'Aimee Beaulieu Transition House', '250-354-4357', null, '778-608-3900', 'Transition House', 'From BC transition houses CSV'),
  ('monarch-place-50', 'New Westminster', 'W.I.N.G.S. Fellowship Ministries (Women in Need Gaining Strength)', 'Monarch Place', '604-521-1888', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('sage-transition-house-51', 'North Vancouver', 'North Shore Crisis Services Society', 'Sage Transition House', '604-987-3374', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('cindy-taylor-safe-home-52', 'Oliver', 'Desert Sun Counselling & Resource Centre Society', 'Cindy Taylor Safe Home', '250-485-7777', null, '250-498-2538', 'Safe Home', 'From BC transition houses CSV'),
  ('parksville-safe-home-53', 'Parksville', 'Haven Society', 'Parksville Safe Home', '250-586-4718', '1-888-756-0616', '250-756-0616', 'Safe Home', 'From BC transition houses CSV'),
  ('pearl-s-safe-home-54', 'Pemberton', 'PearlSpace Support Services Society', 'Pearl''s Safe Home', '604-892-5711', '1-877-890-5711', null, 'Safe Home', 'From BC transition houses CSV'),
  ('hughes-house-55', 'Penticton', 'South Okanagan Women in Need Society', 'Hughes House', '250-493-7233', '1-800-814-2033', null, 'Transition House', 'From BC transition houses CSV'),
  ('okanagan-nation-emergency-transition-house-56', 'Penticton (on-reserve)', 'Okanagan Nation Family Intervention and Services Society', 'Okanagan Nation Emergency Transition House', '250-493-4902', '1-877-493-4909', null, 'Transition House', 'From BC transition houses CSV'),
  ('oomiiqsu-57', 'Port Alberni', 'Huu-ay-aht First Nations', 'Oomiiqsu', '250-736-5066', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('port-alberni-transition-house-58', 'Port Alberni', 'Sage Haven Society', 'Port Alberni Transition House', '250-724-2223', null, '250-206-1011', 'Transition House', 'From BC transition houses CSV'),
  ('port-hardy-safe-home-59', 'Port Hardy', 'North Island Crisis and Counselling Centre Society', 'Port Hardy Safe Home', '250-230-1647', null, '250-949-8333', 'Safe Home', 'From BC transition houses CSV'),
  ('grace-house-60', 'Powell River', 'Powell River and Region Transition House Society', 'Grace House', '604-485-9773', null, '604-485-5335', 'Transition House', 'From BC transition houses CSV'),
  ('dzee-ba-yugh-safe-house-heart-house-61', 'Prince George', 'Carrier Sekani Family Services', 'Dzee Ba''yugh Safe House (Heart House)', '778-924-0004', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('harmony-house-prince-george-62', 'Prince George', 'Phoenix Transition Society', 'Harmony House Prince George', '236-423-3335', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('phoenix-transition-house-63', 'Prince George', 'Phoenix Transition Society', 'Phoenix Transition House', '250-563-7305', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('amber-house-64', 'Prince George', 'Prince George and District Elizabeth Fry Society', 'Amber House', '250-562-5868', '1-866-563-1113', null, 'Transition House', 'From BC transition houses CSV'),
  ('ravens-keep-transition-house-65', 'Prince Rupert', 'North Coast Transition Society', 'Ravens Keep Transition House', '250-627-8588', null, '250-600-1983', 'Transition House', 'From BC transition houses CSV'),
  ('cindy-parolin-safe-home-66', 'Princeton', 'Princeton Family Services Society', 'Cindy Parolin Safe Home', '250-295-8211', null, '250-295-3126', 'Safe Home', 'From BC transition houses CSV'),
  ('amata-transition-house-67', 'Quesnel', 'Amata Transition House Society', 'Amata Transition House', '250-992-3385', null, '250-992-7321', 'Transition House', 'From BC transition houses CSV'),
  ('forsythe-house-a-safe-place-68', 'Revelstoke', 'Revelstoke Women''s Shelter Society', 'Forsythe House - A Safe Place', '250-837-1111', null, '250-837-4382', 'Transition House', 'From BC transition houses CSV'),
  ('nova-transition-house-69', 'Richmond', 'Chimo Community Services Society', 'Nova Transition House', '604-270-4911', '877-374-0742', null, 'Transition House', 'From BC transition houses CSV'),
  ('salmo-safe-home-70', 'Salmo', 'Salmo Community Resource Society', 'Salmo Safe Home', '250-357-2277', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('shuswap-area-women-s-shelter-71', 'Salmon Arm', 'Shuswap Area Family Emergency Society', 'Shuswap & Area Women''s Shelter', '250-832-9616', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('salt-spring-island-transition-house-72', 'Salt Spring Island', 'Islanders Working Against Violence Society', 'Salt Spring Island Transition House', '250-537-0735', '1-877-435-7544', null, 'Transition House', 'From BC transition houses CSV'),
  ('yew-transition-house-73', 'Sechelt', 'Sunshine Coast Community Services Society', 'Yew Transition House', '604-885-2944', '1-877-885-2949', '604-885-5128', 'Transition House', 'From BC transition houses CSV'),
  ('passage-transition-house-74', 'Smithers', 'Northern Society for Domestic Peace', 'Passage Transition House', '250-847-2595', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('annie-s-place-75', 'Sooke', 'Sooke Transition House Society', 'Annie''s Place', '250-642-2591', null, '778-966-2591', 'Transition House', 'From BC transition houses CSV'),
  ('ama-house-for-older-women-76', 'South Surrey', 'Atira Women''s Resource Society', 'Ama House for Older Women', '604-542-5992', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('pearl-s-place-transition-house-77', 'Squamish', 'PearlSpace Support Services Society', 'Pearl''s Place Transition House', '604-892-5711', '1-877-890-5711', null, 'Transition House', 'From BC transition houses CSV'),
  ('shimai-transition-house-78', 'Surrey', 'Atira Women''s Resource Society', 'Shimai Transition House', '604-581-9100', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('maxxine-wright-shelter-79', 'Surrey', 'Atira Women''s Resource Society', 'Maxxine Wright Shelter', '604-619-9188', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('virginia-sam-transition-house-80', 'Surrey/Newton', 'Options Community Services Society', 'Virginia Sam Transition House', '604-572-5116', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('evergreen-transition-house-81', 'Surrey/Whalley', 'Options Community Services Society', 'Evergreen Transition House', '604-584-3301', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('three-sisters-haven-house-82', 'Telegraph Creek (on-reserve)', 'Tahltan Health and Social Services Authority', 'Three Sisters Haven House', '250-235-3120', '1-888-414-2836', null, 'Transition House', 'From BC transition houses CSV'),
  ('ksan-house-83', 'Terrace', 'Ksan House Society', '''Ksan House', '250-635-6447', null, '250-641-7233', 'Transition House', 'From BC transition houses CSV'),
  ('wins-transition-house-84', 'Trail', 'Trail Family and Individual Resource Centre Society', 'WINS Transition House', '250-364-1543', null, '250-364-2326', 'Transition House', 'From BC transition houses CSV'),
  ('tumbler-ridge-safe-home-85', 'Tumbler Ridge', 'South Peace Community Resources Society', 'Tumbler Ridge Safe Home', '250-242-8208', null, null, 'Safe Home', 'From BC transition houses CSV'),
  ('westcoast-transition-house-86', 'Ucluelet', 'Westcoast Community Resources Society', 'Westcoast Transition House', '250-726-2020', '1-877-726-2080', '250-266-0187', 'Transition House', 'From BC transition houses CSV'),
  ('ada-s-place-87', 'Valemount', 'Robson Valley Community Services Society', 'Ada''s Place', '1-844-324-2004', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('mcbride-safe-home-88', 'Valemount', 'Robson Valley Community Services Society', 'McBride Safe Home', '1-844-324-2004', null, '250-569-2266', 'Safe Home', 'From BC transition houses CSV'),
  ('katherine-s-house-89', 'Vancouver', 'Atira Women''s Resource Society', 'Katherine''s House', '778-984-2021', null, '604-531-6314', 'Transition House', 'From BC transition houses CSV'),
  ('pierce-house-90', 'Vancouver', 'Atira Women''s Resource Society', 'Pierce House', '604-267-9131', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('deborah-s-gate-91', 'Vancouver', 'Governing Council of the Salvation Army in Canada', 'Deborah''s Gate', '604-347-9500', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('kate-booth-house-92', 'Vancouver', 'Governing Council of the Salvation Army in Canada', 'Kate Booth House', '604-872-7774', null, '604-872-0772', 'Transition House', 'From BC transition houses CSV'),
  ('helping-spirit-lodge-93', 'Vancouver', 'Helping Spirit Lodge Society', 'Helping Spirit Lodge', '604-872-6649', null, '604-325-2171', 'Transition House', 'From BC transition houses CSV'),
  ('nisa-home-94', 'Vancouver', 'Nisa Foundation', 'Nisa Home', '1-888-456-8043 ext. 402', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('peggy-s-place-95', 'Vancouver', 'The Kettle Friendship Society', 'Peggy''s Place', '604-430-5202', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('vancouver-rape-relief-women-s-shelter-96', 'Vancouver', 'Vancouver Rape Relief Society', 'Vancouver Rape Relief & Women''s Shelter', '604-872-8212', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('joy-aitkens-safe-home-97', 'Vanderhoof', 'Omineca Safe Home Society', 'Joy Aitkens Safe Home', '250-567-9512', null, '250-567-9959', 'Safe Home', 'From BC transition houses CSV'),
  ('vernon-women-s-transition-house-98', 'Vernon', 'Archway Society for Domestic Peace', 'Vernon Women''s Transition House', '250-542-1122', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('cridge-transition-house-for-women-99', 'Victoria', 'Cridge Centre for the Family', 'Cridge Transition House for Women', '250-479-3963', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('older-women-s-safe-home-100', 'Victoria', 'Victoria Women''s Transition House Society', 'Older Women''s Safe Home', '250-385-6611', null, '250-592-2927', 'Safe Home', 'From BC transition houses CSV'),
  ('victoria-women-s-transition-house-101', 'Victoria', 'Victoria Women''s Transition House Society', 'Victoria Women''s Transition House', '250-385-6611', null, '250-592-2927', 'Transition House', 'From BC transition houses CSV'),
  ('help-and-hope-transition-house-102', 'Watson Lake (Yukon - also serves Northern BC)', 'Help and Hope for Families Society', 'Help and Hope Transition House', '867-536-7233', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('west-kelowna-second-stage-103', 'West Kelowna', 'Central Okanagan Emergency Shelter Society', 'West Kelowna Second Stage', '250-763-1040', null, '236-970-0704', 'Transition House', 'From BC transition houses CSV'),
  ('westshore-safe-house-104', 'Westshore', 'Victoria Women''s Transition House Society', 'Westshore Safe House', '250-385-6611', null, null, 'Safe House', 'From BC transition houses CSV'),
  ('maries-safe-home-105', 'Whistler', 'PearlSpace Support Services Society', 'Maries Safe Home', '1-877-890-5711', '1-877-890-5711', null, 'Safe House', 'From BC transition houses CSV'),
  ('durrant-house-106', 'White Rock', 'Atira Women''s Resource Society', 'Durrant House', '604-531-9151', null, null, 'Transition House', 'From BC transition houses CSV'),
  ('chiwid-transition-house-107', 'Williams Lake', 'Cariboo Friendship Society', 'Chiwid Transition House', '250-398-5658', null, '250-398-6831', 'Transition House', 'From BC transition houses CSV')
on conflict (id) do nothing;
